import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="nav">
          <a href="/Pagina1" id="">Pagina 1</a>
          <a href="/Pagina2">Pagina 2</a>
        {children}
        </nav>
      </body>
    </html>
  );
}
